### ISSUE TITLE
tick display has missing data

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#11]
http://89.38.98.214:7004/explorer/tick/14105743 data is missing at least nfflaamalrwkkawknycswswuiwgbsalktvwuyxzgggjiqadopammqcvcvjro

following is what the websockets returns and what is displayed does not match  

{"tick":14105743,"utc":1716931390,"spectrum":"0000000000000000000000000000000000000000000000000000000000000000","qchain":"0000000000000000000000000000000000000000000000000000000000000000","tx":[{"txid":"pjdyqustresyvevkkrmcygkeuagcycvebptegnxvogbbsukbqhxyuyadrwgh","tick":14105743,"utc":1716931390,"src":"TVYZALUOUGBRQCFWVSDZXKCAXFODDNAVMTQLYNPUYDETIADGDAYCYOEAYVDG","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"1a952c8d1b8672e1f886d09daeeaf0deb9d9f4529b7be47efeb3eef938e1ca03","command":"txidrequest"},{"txid":"jnmzqgpayutjabdtwzuwmtjtbxhdysksfwjnzmelmepgowcggwnqqxgheztc","tick":14105743,"utc":1716931390,"src":"AYQSMQJZCZUJYASLGWAXGUCCMPACCDDFFFTJAIFXSEUJBQWAUUJVKCEGINBC","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e02bd35d4726245d3bf3d4ab9512ae75ac62df9bc41f276","command":"txidrequest"},{"txid":"vgotrrvktfpqreqeotkkylgzzemdyxvederyhinkcaxkyvjzdvkwwnteojlh","tick":14105743,"utc":1716931390,"src":"LGZZFKDEAHXJSAEZNWEZZHNTNPGDXSUKOWUEPOCMKEQPUZIZFSJDGVKCLCWO","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d6370756c6e00aebd6c1b2534e84d620b76323370f0ee7623efe8063b","command":"txidrequest"},{"txid":"admyfejepazkrgizzyhuijzimllahqposqljbmuzdfdxoanreehzkafdozng","tick":14105743,"utc":1716931390,"src":"SPECJVLASVEPUGKQVXOPURMJUWYBLXAFWHPVEUHBVGAGUIZDJULCOZNGEQIC","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"5ff46af2b20b763217cc427d5c46249621e3fae343f085de9239ed5c176f4522","command":"txidrequest"},{"txid":"etrckgbtohcwiafrfuanhownjdacykspcpiuvpwuucyvekequpgnzinaxbsj","tick":14105743,"utc":1716931390,"src":"RTEKBCGYJICVWFDKDJOOVSBOATIBEPIHUAWGGJPNIAXKKTNDDWLCDLTGWDVJ","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e0214e822e2bef25adc28454464b4d6a4f595732f5ac891","command":"txidrequest"},{"txid":"gkqbfinavxtnwbeplywbtjtrzodbpxjpcbrqhvdxxecorbchgusrqrvfrvji","tick":14105743,"utc":1716931390,"src":"FXLJVDBFYSXPDDYUNGAPXFKFEELCMRIMHVNOTECUIDTHSBQZPKNCSPLGTNNE","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e02300f3e212db4945f219a1d8862bdb420b531b654ccf2","command":"txidrequest"},{"txid":"mzgiglmwcqvrqayvljzwtpqmjrafpvjdngsycadebdjzohluijdpoenckpgl","tick":14105743,"utc":1716931390,"src":"DMOYYNCDBOIEIGXHWDSJYLHKPABADYIYXUTCCKNAMCBEAXXSQVEMCCDELEAB","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e02be7a75c90276a49716e5e40554a97b4b9e290c7e5bf5","command":"txidrequest"},{"txid":"jbuyxbbsgdmvrflagrjeykmyaudabcsphhzceshnsacxggypxgoghfheqgvf","tick":14105743,"utc":1716931390,"src":"DRELJDXOQFDAHCPAOGSXGSYFTMUAXMHYRDBJRKUYUDQKHZYVTXWQGNUFTECO","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e0253bfc21aa13c44ae380ee751dcc0d57dad005c2b2b1d","command":"txidrequest"},{"txid":"zxhssoyjekwufgituktxxlhbocoawzokrqtsbpknmghtwoieaxqmxjneozxg","tick":14105743,"utc":1716931390,"src":"QUJXJCNMKBTNPGPYYXHYUTAOONIBWAFEHPNPUGPTKDJAWOTAGXKNHAOGPQTA","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"db50aed1865423901085517ea86b98bc02f21e7fabdd20a0df4a421c86c0c2cd","command":"txidrequest"},{"txid":"jumukbaokbcacgpoltzwylhypklcuzdykeyuqfzjrecyfwerbbqljoadijje","tick":14105743,"utc":1716931390,"src":"DMRKLYUUQWXNGBQUQBHWSMUJORGCOJQYQINFEUDMPANYZAJILKBQRXYAKNTC","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d6370756c6e00aaaf4be5959fc9440bc779608c424235111ec9a28643","command":"txidrequest"},{"txid":"srcxwxcqrcaotcxxehsmslfdedwadkrynjssfejhqesrnpjtgfhijrnbjxvm","tick":14105743,"utc":1716931390,"src":"ZMHBAXNKUKZUVAXLEZTZFEAQNCXCWVKPQUUTNEJBFDBFAGBBWZCLGSMCUWJL","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637564616e02bde39bb23edfe7db7c055b8c2158db8379e12daeed20","command":"txidrequest"},{"txid":"deuwmuycqbnhrbetdglvrjprhoebffcuinykoylckbrgyzrtmjscnvtbowdc","tick":14105743,"utc":1716931390,"src":"YUFJEDKACXIUCHTYGKEJCLWMUPRDDBPMITRWBSZVGFMLTEPFNFDSACBBLIDM","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d637075776e00c04971e0fe6f7932ac7f405a08be00e261450b12b103","command":"txidrequest"},{"txid":"ysqxveonacbgjbkhsbucmfmonxfbibuzdzbahamdyafishldbtwcxqudlvej","tick":14105743,"utc":1716931390,"src":"SZOBAJRSECPHIGEOWUYJRHJQAOGDQKJLYNMNXWKPBABNXLKBFFUABMQFHDZF","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"5848ccc52c6c31e998c12ece4b8eeab437b6340e53fed08c6c5ed93e7b38ab7e","command":"txidrequest"},{"txid":"qiexugycrsrxybspudrjqepiqkzcyspupvfwehdvwgtfrphsjvnfsozdtqda","tick":14105743,"utc":1716931390,"src":"LNTAMQAIGIXGMBBZTZFKFVXGJHVBIAGYLXBISOVKOGGRFNRNRPBQSLWEIRLJ","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d6370756c6e000190700794ccab7b09f6da311387fd7f81ac92a901ad","command":"txidrequest"},{"txid":"hgrwmkwxnfandhpdurqevhmshdtfsykiyswpmvhsmczytzdhvrseepobblye","tick":14105743,"utc":1716931390,"src":"FAYNFJJEFNCNJBHCYHQBHHINSJTBQTKBDLIWYZIZHATBYHEMLLSVNKIGCUWF","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"7523be3c96da1c2dece306c8a8f47c913ff6cbaad03782f8c50bce7bc1b391cf","command":"txidrequest"},{"txid":"nvnrwrnpukkmfgjaxcwizahrghsblxdzzvulbdixcgizhvjlwvdblbpgvegb","tick":14105743,"utc":1716931390,"src":"NTMXEZIDEXVEDAYSQDJOAHJDTBZANMCYSVILDGQDTCVMXBBXMATDSVSDWEKM","dest":"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ","amount":"0","type":0,"extralen":32,"extra":"716c692d6370756c6e009db4d48fa5a7846f6acb3e6848c022e5beebf9d82a75","command":"txidrequest"},{"txid":"nfflaamalrwkkawknycswswuiwgbsalktvwuyxzgggjiqadopammqcvcvjro","tick":14105743,"utc":1716931390,"src":"YVNAKBGCLHJKHETVCWAFIPTVKCTASRLTOTWCOIOFDAWUUSAJNOBQWBEEJNNB","dest":"CFBMEMZOIDEXQAUXYYSZIURADQLAPWPMNJXQSNVQZAHYVOPYUKKJBJUCTVJL","amount":"1000000","type":0,"extralen":0,"extra":"","command":"txidrequest","status":"confirmed"}]}

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer/tick/14105743
please check here @Qsilver97

**Comment by real-venus** [comment]
![image](https://github.com/Qsilver97/website/assets/153379385/f166c2e2-ac3e-405b-9b64-a69e8ff1e314)

**Comment by Qsilver97** [comment]
empty tick or server issue not UI
