### ISSUE TITLE
address summary data missing the number of incoming and outgoing transfers, should be merged into Incoming and Outgoing boxes

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#13]
also the tick that the entity data is from is missing

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer/address/YGHKVOQXXKVWXEYIJJRSMHWDJITBANJEJTBRNBXZYANLOFRHEZJTNOUBLHHC
please check here @Qsilver97

**Comment by real-venus** [comment]
![image](https://github.com/Qsilver97/website/assets/153379385/cea6a4b4-dcc1-48b8-a028-bfa5e8388c5e)
Trading hours must be displayed

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/explorer/address/BOJOBRHAZILUCDADNGBXYUIYHNIDCKBSQEWGUFCAJASIOPFNBMWWXDJHCCTC
check again @Gaussian120

**Comment by Qsilver97** [comment]
only problem left is
Incomes and Outcomes boxes should become Number fields in Incoming and Outgoing

Incoming xxx
Number yyy
Latest xxx

Outgoing xxx
Number yyy
Latest xxx

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/
please check @Qsilver97

**Comment by Qsilver97** [comment]
closed
