### ISSUE TITLE
token balances missing from address

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#14]
no token balances

also the QU value and USD value of the tokens and QU should be displayed
that way user will know the total QU value of all tokens+QU and also approx USD value

**Comment by evoandro** [comment]
Can you add a command to get balances from an address like below?
balances <address>

**Comment by Qsilver97** [comment]
the normal <address> returns all the balances. you want the same data just more streamlined?

**Comment by evoandro** [comment]
well, I see

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer/address/HZKGWJFHPUGRIBMZQBTHPXVQOGLANSERJVWIQYONFHJWAFJRATWHZIQFIYRM
please check here @Qsilver97

**Comment by real-venus** [comment]
resolved
