### ISSUE TITLE
QU richlist is hard to navigate

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#15]
QU richlist has a lot of entries and if user wants to see around rank 1000 it takes forever to scroll there
websockets has a way to query a range of the richlist, using that an efficient way to get to any point in richlist can be made

probably a box to input the starting rank would help a lot

**Comment by evoandro** [comment]
how about pagination?

**Comment by Qsilver97** [comment]
yes, pagination is perfect!

**Comment by evoandro** [comment]
http://89.38.98.214:7004/richlist/QWALLET
please check here @Qsilver97

**Comment by real-venus** [comment]
resolved
