### ISSUE TITLE
overview page problems

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#16]
empty ticks box is unreadable with all the tick numbers merged together
the recenttx list is hard to understand and the filtering is not working
in websockets the recenttx has a filter value you can send and it filters for that specific SC transactions

the txid source and destination should be more readable. maybe using the full width of the screen and putting the empty ticks list below it?

**Comment by evoandro** [comment]
recenttx   [num [scfilter]]  -> lists recent tx. num (defaults to 100, max 1000) scfilter limits to SC index 

please explain this command in more detail

**Comment by Qsilver97** [comment]
recenttx 100 will return the most recent 100 tx for nonzero QU transfers
recenttx 1000 will return the most recent 1000 tx
recenttx 100 1 will return the most recent 100 tx sent to BAAAAA address, the SC address for contract 1
recenttx 100 4 will return the most recent 100tx sent to EAAAA address, SC address for contract 4

**Comment by evoandro** [comment]
Is there a command to send all recent transactions in once, not only QU transfer or based on contract index?

**Comment by Qsilver97** [comment]
recenttx 100 
above will return the 100 most recent transactions, of whatever type

**Comment by evoandro** [comment]
please check again @Qsilver97 
http://89.38.98.214:7004/explorer

**Comment by real-venus** [comment]
resolved
