### ISSUE TITLE
scroll bars are way too thin and very hard to slide

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#2]

**Comment by Qsilver97** [comment]
vertical scroll bar fixed
horizontal scroll bar still too thin

**Comment by evoandro** [comment]
let me show screenshot

**Comment by Qsilver97** [comment]
there is no scroll bar!

**Comment by Qsilver97** [comment]
needs a scroll bar with more tokens

**Comment by Qsilver97** [comment]
added explist for the explorer to use as the tokenlist
this way we can support a different set of tokens for the explorer that has bigger capacity

**Comment by evoandro** [comment]
now can scroll

**Comment by Qsilver97** [comment]
can you change the explorer to use the explist command instead of tokenlist?
I want to see how it works with 10 more tokens and it is a good idea to have different lists for explorer and UI

**Comment by evoandro** [comment]
ok

**Comment by evoandro** [comment]
http://89.38.98.214:7006/orderbook/QWALLET
check again

**Comment by Qsilver97** [comment]
I do not see the test tokens
result from explist is: {"tokens":["QWALLET","CFB","QX","QTRY","RANDOM","MLM","QFT","QPOOL","QUTIL","TEST1","TEST2","TEST3","TEST4","TEST5","TEST6","TEST7","TEST8","TEST9"]}
