### ISSUE TITLE
search by address.

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#21]
I think a general explorer should have a search function by address.
![image](https://github.com/Qsilver97/website/assets/153379385/f3db4391-ab3b-4797-aa50-9679808ffdbb)

**Comment by real-venus** [comment]
![image](https://github.com/Qsilver97/website/assets/153379385/2649dbbf-999f-456d-bfa4-0e05e5e65edd)

As seen in Solana Explorer, I think the explorer's search function should be implemented like this.

**Comment by evoandro** [comment]
good point
actually, searching by address is working,
but not displayed in placeholder.

**Comment by evoandro** [comment]
fixed @Qsilver97

**Comment by real-venus** [comment]
great
resolved
