### ISSUE TITLE
Need to show time when Latest transaction.

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#22]
![image](https://github.com/Qsilver97/website/assets/153379385/76ed780e-140f-42bf-9f89-226d5dbb6214)
I think it is standard that Latest Transactions must include time.
As shown below
![image](https://github.com/Qsilver97/website/assets/153379385/e05572d5-53fc-4ba2-9cf6-13bbf028319c)

**Comment by evoandro** [comment]
what do you think @Qsilver97 ?

**Comment by Qsilver97** [comment]
having the empty ticks on the left and the recenttx on the right makes it hard to read. having each be the full width would be better. 

then there would be more room and it is useful to see how long ago the transaction was, UTC time is included in transactions data

**Comment by evoandro** [comment]
http://89.38.98.214/explorer

please check here

**Comment by Qsilver97** [comment]
I talked about the current Tick at the bottom of the screen, would be good to bring it to top of page and also add the hours/min/sec

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
please check here again @Qsilver97 @Gaussian120

**Comment by real-venus** [comment]
![image](https://github.com/Qsilver97/website/assets/153379385/4bc6e96e-5f19-4b3e-9483-1e9eeb767c94)

**Comment by real-venus** [comment]
Instead of displaying the time like that in the picture, it should be displayed in the form of seconds ago, days ago, or weeks ago.

**Comment by real-venus** [comment]
ex:
3 sec ago
2 day ago
5 week ago

**Comment by evoandro** [comment]
when mouse hover, it works
anyway, let's discuss with @Qsilver97

**Comment by Qsilver97** [comment]
almost there!
just need human readable time

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
http://89.38.98.214:7004/explorer/address/EEWCBEZNLEITWFWVEOFBLKHVXTAARMIGJNXICDIRIFDBUDGFXEYABULCFXAN
check here

**Comment by Qsilver97** [comment]
yes!
