### ISSUE TITLE
I think this is an unnecessary item

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#23]
![image](https://github.com/Qsilver97/website/assets/153379385/b91008ed-23c1-4c7f-8eb3-2178d6b7b5dd)

**Comment by real-venus** [comment]
If we need to display recent transactions, it would be a good idea to implement it as follows.
![image](https://github.com/Qsilver97/website/assets/153379385/e5bf2ad9-e1f1-47e1-9de7-b4c9db820ef2)

**Comment by Qsilver97** [comment]
we can put in the ave time per tick for last 100 ticks and time taking for current tick.
I will add this info to the "network" request

**Comment by Qsilver97** [comment]
added new fields to the "network" command
{"latest":14130570,"validated":14130568,"txdata":14130568,"epoch":111,"last10":70,"diff":18,"avelag":7.0,"estimate":4} 
last10 is the time taken for last 10 ticks
diff is the current time difference from latest tick timestamp.
however this is bigger than the actual time from last tick as there is a lag of about 2 ticks for the tick timestamp versus realtime
so the estimate field adjusts for this and while it sometimes goes negative it seems to usually track the time elapsed decently

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
please check here @Qsilver97 @Gaussian120

**Comment by real-venus** [comment]
resolved
