### ISSUE TITLE
in overview tab, recent transaction - dropdown error

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#24]
![image](https://github.com/Qsilver97/website/assets/153379385/b3a41199-4432-44f3-9103-224e80bb18f2)
Why are there no QWALLET items?

**Comment by Qsilver97** [comment]
that dropdown is a filter based on SC index
only SC should be on that list, so CFB should not be on the list
by passing in the scindex to recenttx, only tx for that SC will be returned and it is a very useful way to search for QX trades and QUTIL sendmany txid

**Comment by evoandro** [comment]
@Qsilver97, how can I fetch all SC and indexes of the SC?
I have used the tokens for the dropdown.

**Comment by Qsilver97** [comment]
If you iterate the explist command and for each one do a tokenissuer, the SC return the index and normal tokens returns issuer. If you really need it, I could make a command to return just the SC

or maybe we add an option to explist SC? that would return just the SC

**Comment by evoandro** [comment]
it will be helpful, thank you

**Comment by Qsilver97** [comment]
explist SC returns the SC in order, first one is id 1

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
please check here @Qsilver97 @Gaussian120

**Comment by real-venus** [comment]
resolved
