### ISSUE TITLE
what does "Type" mean  in recently transaction Panel ?

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#25]
![image](https://github.com/Qsilver97/website/assets/153379385/ed9d49c4-d21f-4eea-9ff8-f6f67cf5f4b1)

**Comment by real-venus** [comment]
I think it will cause confusion for first-time users.

**Comment by evoandro** [comment]
> I think it will cause confusion for first-time users.

I am not sure, just implemented by prev dev.
@Qsilver97, what do you think?

**Comment by Qsilver97** [comment]
type is not so useful 
elapsed time is. so probably add a time column (elapsed is the preference) and remove the type column

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
please check here @Qsilver97 @Gaussian120

**Comment by real-venus** [comment]
resolved.
however, the solution was to completely remove that function( type ) from the screen.
