### ISSUE TITLE
Displays the price change rate in the last few hours

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#26]
The most basic and most important function in Explorer is missing.
![image](https://github.com/Qsilver97/website/assets/153379385/2251d61c-d15f-4de3-8719-ed1da4c94c70)

**Comment by real-venus** [comment]
i mean:
![image](https://github.com/Qsilver97/website/assets/153379385/549bc7db-0c97-4451-96d0-5156719afd5f)

**Comment by real-venus** [comment]
![image](https://github.com/Qsilver97/website/assets/153379385/6f66ba48-529c-43f0-a331-19a28e847690)

**Comment by evoandro** [comment]
good point.
@Qsilver97, do you agree with this?

**Comment by Qsilver97** [comment]
seems a good idea.

**Comment by evoandro** [comment]
could you add the price change rate to the marketcap command? @Qsilver97

**Comment by Qsilver97** [comment]
we can close this as not really needed
