### ISSUE TITLE
Margin error (Empty ticks)

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#31]
![image](https://github.com/Qsilver97/website/assets/153379385/81b3f404-dba5-4d13-a94c-392e9d343719)
The margins between numbers are so small that it is difficult to distinguish them.

**Comment by evoandro** [comment]
fixed, please check again, @Gaussian120

**Comment by Qsilver97** [comment]
The new layout is better.
The current tick at the very bottom of screen is actually pretty important. It should be top of the screen
probably at the same level as the Overview/Downloads/Order Book/Richlist menu, seems there is room next to the Qsilver logo

**Comment by evoandro** [comment]
check again
http://89.38.98.214:7004/

**Comment by Qsilver97** [comment]
yes! layout is much better!
I hope the token prices can be made more understandable

**Comment by real-venus** [comment]
good
