### ISSUE TITLE
History transaction view page

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#32]
https://github.com/Qsilver97/website/assets/153379385/52e50690-adfd-4ef5-bf7d-69a81405753b

**Comment by real-venus** [comment]
Why isn't there a feature like this?
There should be a page where you can see records of who sent or received tokens to whom and when.

**Comment by Qsilver97** [comment]
address history should do this have you checked latest version by refreshing page?

**Comment by Qsilver97** [comment]
I see address history
