### ISSUE TITLE
richlist numbers are different widths

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#35]
seems a monospaced font makes more sense for the richlist display

**Comment by evoandro** [comment]
I think, it seems fixed
please give me the screenshot, @Qsilver97

**Comment by Qsilver97** [comment]
<img width="163" alt="image" src="https://github.com/Qsilver97/website/assets/152714424/624b92f0-5891-4e48-94ae-00d8392620e9">
Not sure why but the numbers are not aligned

**Comment by evoandro** [comment]
oh, I see
http://89.38.98.214:7004/richlist/QU
fixed now

**Comment by Qsilver97** [comment]
yes! feels much better to be monospace
