### ISSUE TITLE
Switching function to search button

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#39]
It is a meaningless search button.
It's unnecessary.

![image](https://github.com/Qsilver97/website/assets/153379385/71facb50-7c92-4aa4-a7d7-c5dfcd377ee0)
![image](https://github.com/Qsilver97/website/assets/153379385/e0905d6e-bcca-447a-85fe-c193bdd32845)

**Comment by real-venus** [comment]
Why do we need this?
You can delete unnecessary things.
If you really need it, I think it should be placed as a search button on mobile phones and in horizontal scrolling direction on desktops.

**Comment by Qsilver97** [comment]
we will need it when there are 500 tokens!
