### ISSUE TITLE
horizontal scrolling of tokens is very confusing

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#4]
you click on one token and it flips to a different set, there is no visual continuity
the ... does not do anything

**Comment by evoandro** [comment]
fixed

**Comment by Qsilver97** [comment]
feels better, but the ... does not do anything yet, not sure what it should do

**Comment by evoandro** [comment]
not built yet

**Comment by evoandro** [comment]
http://89.38.98.214:7006/orderbook/RANDOM
development url

**Comment by evoandro** [comment]
http://89.38.98.214/orderbook/QX
check again here

**Comment by Qsilver97** [comment]
fixed!
