### ISSUE TITLE
blank screen happens often

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#40]
Often the qexplorer just shows a blank screen
sometimes after a while it displays a page but usually a refresh is needed and it takes a long time for a page to appear

maybe we show the overview page without the chart filled out and then update the chart when the chart data arrives? not sure but there also seems to be some sort of hang problem

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/
please check this production environment

**Comment by real-venus** [comment]
resolved
