### ISSUE TITLE
 Downloads should be categorized 

### ISSUE THREAD

**Issue by Mazzya** [Qsilver97/website#41]
I think the display should be spaced out a little to simplify reading and finding the right versions. This will make things easier for newbie users.

- Android releases :
----------- 

- Windows releases :
-----------

- Linux releases :
-----------

etc...

![qexplorer_downloads](https://github.com/Qsilver97/website/assets/41023812/2974a216-495c-4c85-a3f2-9f464ddc5e38)

**Comment by evoandro** [comment]
good point.
what do you think @Qsilver97 ?

**Comment by Qsilver97** [comment]
yes, very good

**Comment by evoandro** [comment]
ok, I will do this

**Comment by evoandro** [comment]
http://89.38.98.214:7004/download
please check here @Qsilver97

**Comment by Qsilver97** [comment]
works!!
