### ISSUE TITLE
txid search page does not show SC data

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#43]
exrqbmphjqrkqbbqfqzyvnmenmxabqfwqijmlsvyyexxtorzwzcbxhzamoga

above should show sc data

**Comment by evoandro** [comment]
you mean sctx? @Qsilver97

**Comment by Qsilver97** [comment]
yes, that is a token transfer but without the sctx data cannot tell anything about it

**Comment by Qsilver97** [comment]
works now!
