### ISSUE TITLE
https does not work due to http proxy

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#45]

**Comment by evoandro** [comment]
https://qsilver.org/
you mean this? @Qsilver97

**Comment by Qsilver97** [comment]
https://qexplorer.qsilver.org

currently we tell people to use http but many browsers automatically change it to http

**Comment by evoandro** [comment]
I will config this

**Comment by Qsilver97** [comment]
plz coordinate deployment timing with @termos as we need to change the LB mapping to https at the same time

**Comment by evoandro** [comment]
I got it

**Comment by Qsilver97** [comment]
actually termos said it is ready anytime, so you can push https code anytime
it should just work

**Comment by evoandro** [comment]
well, I understood

**Comment by evoandro** [comment]
discussed with termos and fixed now
and need a new issue for the download page
https://qexplorer.qsilver.org/explorer
please check here.

**Comment by Qsilver97** [comment]
https city

**Comment by Qsilver97** [comment]
almost works, just download page not working now

**Comment by Qsilver97** [comment]
works
