### ISSUE TITLE
SC filter seach is off by 1

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#49]
QX is 1
QTRY is 2

but the searching is doing QX is 0

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/
please check @Qsilver97

**Comment by Qsilver97** [comment]
sorry for ambiguity, we still need to search for QU tx, recenttx without parameter.
that way people can see all the recenttx

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/explorer
please check again

**Comment by Qsilver97** [comment]
fixed
