### ISSUE TITLE
SC number is randomly generated for tokens

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#5]
It should be the issuer address for normal tokens and SC index for smart contracts

**Comment by evoandro** [comment]
where can I get SC number?

**Comment by Qsilver97** [comment]
websockets tokenissuer QX will return {"issuer":"QubicSmartContract","contractid":"1"} 
tokenissuer QWALLET returns {"issuer":"74ad8dacaadc6b2acfcdee2e467b2238cf7079484853c4c95f29b871935bb219","address":"QWALLETSGQVAGBHUCVVXWZXMBKQBPQQSHRYKZGEJWFVNUFCEDDPRMKTAUVHA"} 

So the user made tokens and SC shares return different type of data. Since anybody can issue a token with the same name, it is important that people know the issuer for user tokens and SC number for smart contracts

**Comment by evoandro** [comment]
check again

**Comment by Qsilver97** [comment]
fixed. problem was server side
