### ISSUE TITLE
typo issue for tokenprices

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/website#50]
"min" -> "bid"
"max" -> "ask"

the prices are highest bid and lowest ask

**Comment by Qsilver97** [comment]
would be nice if each display box was hyperlinked to the corresponding orderbook, but not required as already very good to have this summary right in one place

**Comment by evoandro** [comment]
https://qexplorer.qsilver.org/
please check @Qsilver97

**Comment by Qsilver97** [comment]
fixed
