### ISSUE TITLE
transaction time display error.

### ISSUE THREAD

**Issue by real-venus** [Qsilver97/website#55]
![image](https://github.com/Qsilver97/website/assets/153379385/33871f47-7436-483c-8441-ca158ce58ac4)

**Comment by Qsilver97** [comment]
seems just the recenttx time is converted strangely

actually seems it is just using 0 as all are the same time Tue, 20 Jan 1970 21:05:02 GMT

**Comment by evoandro** [comment]
http://89.38.98.214:7004/explorer
please check here @Qsilver97

**Comment by Qsilver97** [comment]
fixed
